/**
 * BJJ domain vocabulary for transcription priming.
 *
 * These terms are passed to the transcription provider so domain language
 * ("berimbolo", "De La Riva", "kimura") is recognised instead of being
 * mangled into nearby English words. 200+ terms across all categories.
 *
 * Categories are kept structured so they can be selectively weighted later;
 * `BJJ_VOCABULARY_FLAT` is the flat list the provider actually consumes.
 */
export const BJJ_VOCABULARY = {
  guards: [
    'De La Riva',
    'Reverse De La Riva',
    'Spider Guard',
    'Lasso Guard',
    'Butterfly Guard',
    'Half Guard',
    'Deep Half',
    'Z-Guard',
    'K-Guard',
    'Closed Guard',
    'Open Guard',
    'X-Guard',
    'Single Leg X',
    'Rubber Guard',
    'Worm Guard',
    'Squid Guard',
    'Crab Ride',
    'Lockdown',
    'Collar Sleeve',
    'Shin to Shin',
    'Sit-up Guard',
    'Octopus Guard',
    'Williams Guard',
    'Gubber Guard',
    'Matrix Guard',
    'False Reap',
    '93 Guard',
    'Knee Shield',
    'Paper Cutter Guard',
    'Tornado Guard',
  ],
  passes: [
    'Torreando',
    'Leg Drag',
    'Knee Slice',
    'Knee Cut',
    'Smash Pass',
    'Stack Pass',
    'Double Under',
    'Headquarters',
    'Bullfighter',
    'Over-Under',
    'Cartwheel Pass',
    'Folding Pass',
    'Tilt Pass',
    'Longstep',
    'Float Pass',
    'Body Lock Pass',
    'X-Pass',
    'Toreando',
    'Leg Weave',
    'Backstep Pass',
    'Wrestle Up Counter',
    'Pressure Pass',
    'Matador Pass',
    'Knee Cut Pass',
    'Standing Pass',
  ],
  sweeps: [
    'Scissor Sweep',
    'Flower Sweep',
    'Hip Bump',
    'Pendulum',
    'Sit-up Sweep',
    'Berimbolo',
    'Homer Simpson',
    'Waiter Sweep',
    'Kiss of the Dragon',
    'Sickle Sweep',
    'Tripod Sweep',
    'Lumberjack Sweep',
    'Butterfly Sweep',
    'Hook Sweep',
    'Balloon Sweep',
    'Elevator Sweep',
    'Tomoe Nage',
    'Overhead Sweep',
    'Old School Sweep',
    'Electric Chair',
    'Dogfight Sweep',
    'Tornado Sweep',
  ],
  submissions: [
    'Rear Naked Choke',
    'Guillotine',
    "D'Arce",
    'Anaconda',
    'Kimura',
    'Americana',
    'Omoplata',
    'Triangle',
    'Armbar',
    'Heel Hook',
    'Inside Heel Hook',
    'Outside Heel Hook',
    'Kneebar',
    'Toe Hold',
    'Calf Slicer',
    'Bow and Arrow',
    'Ezekiel',
    'Kata Gatame',
    'Loop Choke',
    'Baseball Bat Choke',
    'North South Choke',
    'Twister',
    'Buggy Choke',
    'Peruvian Necktie',
    'Gogoplata',
    'Banana Split',
    'Estima Lock',
    'Wristlock',
    'Clock Choke',
    'Cross Collar Choke',
    'Bicep Slicer',
    'Japanese Necktie',
    'Von Flue Choke',
    'Aoki Lock',
  ],
  positions: [
    'Mount',
    'Side Control',
    'Back Mount',
    'Turtle',
    'North South',
    'Knee on Belly',
    'Crucifix',
    'Truck',
    'Body Lock',
    'Back Control',
    'Chest to Chest',
    '50-50',
    'Saddle',
    'Inside Sankaku',
    'Outside Ashi',
    'Honey Hole',
    'Twister Side Control',
    'Tripod',
    'High Mount',
    'S-Mount',
    'Technical Mount',
    'Reverse Kesa',
  ],
  concepts: [
    'Base',
    'Posture',
    'Framing',
    'Shrimping',
    'Granby Roll',
    'Hip Escape',
    'Bridge',
    'Elbow-Knee',
    'Connection',
    'Kuzushi',
    'Grips',
    'Underhook',
    'Overhook',
    'Whizzer',
    'Collar Tie',
    'Level Change',
    'Inside Position',
    'Head Control',
    'Pummeling',
    'Hand Fighting',
    'Pressure',
    'Hip Heist',
    'Sprawl',
    'Posting',
    'Re-guard',
    'Frame and Bridge',
    'Two-on-One',
    'Wedge',
    'Hip Switch',
    'Knee Line',
  ],
  slang: [
    'Roll',
    'Spar',
    'Tap',
    'Smash',
    'Scramble',
    'Clinch',
    'Flow Roll',
    'Hard Roll',
    'Shark Tank',
    'King of the Mat',
    'Positional Drilling',
    'Situational Sparring',
    'Guard Pull',
    'Butt Scoot',
    'Invert',
    'Back Step',
    'Sit Up',
    'Stand Up',
    'Oss',
    'Gi',
    'No-Gi',
    'Rashguard',
    'Spazzy',
    'Gas Out',
    'Tap City',
    'Slow Roll',
    'Live Round',
    'Drill',
    'Open Mat',
    'Comp Round',
    'Tap Out',
    'Submission Only',
    'Points Match',
    'Advantage',
  ],
  belts: [
    'White Belt',
    'Blue Belt',
    'Purple Belt',
    'Brown Belt',
    'Black Belt',
    'Stripe',
    'Coral Belt',
  ],
} as const;

export const BJJ_VOCABULARY_FLAT: string[] = Object.values(BJJ_VOCABULARY).flat();
